const Data = {
    status: "success",
    items: [
        {
            id: 1,
            tittle: "Pantuflas Homero",
            price: 25.000,
            image: require ('./Assets/PantuflasHomero.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 2,
            tittle: "Pantuflas Batman",
            price: 25.000,
            image: require ('./Assets/PantuflasBatman.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 3,
            tittle: "Pantuflas Mario Bros",
            price: 25.000,
            image: require ('./Assets/PantuflasMario.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 4,
            tittle: "Pantuflas Bob Esponja",
            price: 25.000,
            image: require ('./Assets/PantuflasBobEsponja.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 5,
            tittle: "Pantuflas Perrito",
            price: 25.000,
            image: require ('./Assets/PantuflasPerrito.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 6,
            tittle: "Pantuflas Escandalosos",
            price: 25.000,
            image: require ('./Assets/PantuflasEscandalosos.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 7,
            tittle: "Pantuflas Mafalda",
            price: 25.000,
            image: require ('./Assets/PantuflasMafalda.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 8,
            tittle: "Pantuflas Minnie",
            price: 25.000,
            image: require ('./Assets/PantuflasMinnie.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 9,
            tittle: "Pantuflas Silvestre",
            price: 25.000,
            image: require ('./Assets/PantuflasSilvestre.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 10,
            tittle: "Pantuflas Garfield",
            price: 25.000,
            image: require ('./Assets/PantuflasGarfield.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 11,
            tittle: "Pantuflas Minnie Rosadas",
            price: 25.000,
            image: require ('./Assets/PantuflasMinnieRosadas.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 12,
            tittle: "Pantuflas Elmo",
            price: 25.000,
            image: require ('./Assets/PantuflasElmo.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 13,
            tittle: "Pantuflas Tazmania",
            price: 25.000,
            image: require ('./Assets/PantuflasTazmania.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 14,
            tittle: "Pantuflas Aguacate",
            price: 25.000,
            image: require ('./Assets/PantuflasAguacate.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 15,
            tittle: "Pantuflas Piolin",
            price: 25.000,
            image: require ('./Assets/PantuflasPiolin.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 16,
            tittle: "Pantuflas Up Hombre",
            price: 25.000,
            image: require ('./Assets/PantuflasUp.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 17,
            tittle: "Pantuflas Up Mujer Rosadas",
            price: 25.000,
            image: require ('./Assets/PantuflasUpViejitaRosadas.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 18,
            tittle: "Pantuflas Dragon Ball Z",
            price: 25.000,
            image: require ('./Assets/PantuflasDragonBallZ.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 19,
            tittle: "Pantuflas Pantera Rosa",
            price: 25.000,
            image: require ('./Assets/PantuflasPanteraRosa.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 20,
            tittle: "Pantuflas Hombre serio",
            price: 25.000,
            image: require ('./Assets/PantuflasSeñor.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 21,
            tittle: "Pantuflas Chimuelo",
            price: 25.000,
            image: require ('./Assets/PantuflasChimuelo.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 22,
            tittle: "Pantuflas Mejor Amiga",
            price: 25.000,
            image: require ('./Assets/PantuflasMejoresAmigas.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 23,
            tittle: "Pantuflas Gato",
            price: 25.000,
            image: require ('./Assets/PantuflasGato.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 24,
            tittle: "Pantuflas Igor",
            price: 25.000,
            image: require ('./Assets/PantuflasIgor.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 25,
            tittle: "Pantuflas Up mujer grises",
            price: 25.000,
            image: require ('./Assets/PantuflasUpViejita.jpg'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 26,
            tittle: "Pantuflas Harry Potter",
            price: 25.000,
            image: require ('./Assets/PantuflasHarryPotter.png'),
            category: "Pantuflas",
            cantidad: 1,
        },
        {
            id: 27,
            tittle: "Babuchas Unicornio",
            price: 30.000,
            image: require ('./Assets/BabuchasUnicornio.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 28,
            tittle: "Babuchas mono",
            price: 30.000,
            image: require ('./Assets/BabuchasMono.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 29,
            tittle: "Babuchas Garras Negras",
            price: 30.000,
            image: require ('./Assets/BabuchasGarrasNegras.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 30,
            tittle: "Babuchas Garras Cafes",
            price: 30.000,
            image: require ('./Assets/BabuchasGarrasCafes.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 31,
            tittle: "Babuchas Garras Grises",
            price: 30.000,
            image: require ('./Assets/BabuchasGarrasGrises.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 32,
            tittle: "Babuchas Sonic",
            price: 30.000,
            image: require ('./Assets/BabuchasSonic.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 33,
            tittle: "Babuchas Amiga Stich",
            price: 30.000,
            image: require ('./Assets/BabuchasStichRosa.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 34,
            tittle: "Babuchas Ecandalosos",
            price: 30.000,
            image: require ('./Assets/BabuchasEscandaloso.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 35,
            tittle: "Babuchas Pantera Rosa",
            price: 30.000,
            image: require ('./Assets/BabuchasPanteraRosa.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 36,
            tittle: "Babuchas Spiderman",
            price: 30.000,
            image: require ('./Assets/BabuchasSpiderman.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 37,
            tittle: "Babuchas Garras Colores",
            price: 30.000,
            image: require ('./Assets/BabuchasGarrasColores.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 38,
            tittle: "Babuchas Perrito",
            price: 30.000,
            image: require ('./Assets/BabuchasPerrito.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 39,
            tittle: "Babuchas Igor",
            price: 30.000,
            image: require ('./Assets/BabuchasBurro.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 40,
            tittle: "Babuchas Conejo",
            price: 30.000,
            image: require ('./Assets/BabuchasConejo.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 41,
            tittle: "Babuchas Pikachu",
            price: 30.000,
            image: require ('./Assets/BabuchasPikachu.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 42,
            tittle: "Babuchas Paw Patrol",
            price: 30.000,
            image: require ('./Assets/BabuchasPawPatrol.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 43,
            tittle: "Babuchas Garras Rosadas",
            price: 30.000,
            image: require ('./Assets/BabuchasGarrasRosa.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 44,
            tittle: "Babuchas Novia Silvestre",
            price: 30.000,
            image: require ('./Assets/BabuchasNoviaSilvestre.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 45,
            tittle: "Babuchas Gato Rosa",
            price: 30.000,
            image: require ('./Assets/BabuchasGatoRosa.jpg'),
            category: "Babuchas",
            cantidad: 1,
        },
        {
            id: 46,
            tittle: "Babuchas Chimuelo",
            price: 30.000,
            image: require ('./Assets/BabuchasChimuelo.png'),
            category: "Babuchas",
            cantidad: 1,
        },
    ],
};

export default Data;